# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/almeida.viraj01@gmail.com/New Pipeline 2026-04-08 13:49")

# COMMAND ----------

# !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

display(spark.sql("SELECT * FROM declarativepipelineordlt.dlt_schema.sample_aggregation_apr_8_1349"))

# COMMAND ----------

# MAGIC %md
# MAGIC # Using this notebook viewing the data we have in our objects in source code folder:

# COMMAND ----------

df = spark.read.table("declarativepipelineordlt.source.orders")
display(df)